/**
 * 引用 Android 系统库，示例如下：
 * import { Context } from "android.content.Context";
 * [可选实现，按需引入]
 */

/* 引入 interface.uts 文件中定义的变量 */
import { MyApiOptions, MyApiResult, MyApi, MyApiSync } from '../interface.uts';

/* 引入 unierror.uts 文件中定义的变量 */
import { MyApiFailImpl } from '../unierror';
import NativeCode from "com.ugreen.bluetooth.NativeCode";
import UGCrashHandler from "com.ugreen.bluetooth.UGCrashHandler";
import Application from "android.app.Application";

export function getMemInfo():Array<number>{
	const context = UTSAndroid.getAppContext();
	let kotlinArray = NativeCode.getMemInfo(context);
	return UTSArray.fromNative(kotlinArray)
}

// 日志callback
export function logCallback(callback:(log:string) => void) {
	const context = UTSAndroid.getAppContext();
	UGCrashHandler.init(context,callback);
	console.log("logCallback initialized");
}

export function testJavaCrash(){
	NativeCode.testJavaCrash();
}