/**
 * 引用 Android 系统库，示例如下：
 * import { Context } from "android.content.Context";
 * [可选实现，按需引入]
 */

/* 引入 interface.uts 文件中定义的变量 */
import { MyApiOptions, MyApiResult, MyApi, MyApiSync } from '../interface.uts';

/* 引入 unierror.uts 文件中定义的变量 */
import { MyApiFailImpl } from '../unierror';
import NativeCode from "com.ugreen.bluetooth.NativeCode";
import FitCloudSDK from "com.ugreen.fitcloudsdk.FitCloudSDK";
import Application from "android.app.Application";

export function getMemInfo():Array<number>{
	const context = UTSAndroid.getAppContext();
	let kotlinArray = NativeCode.getMemInfo(context);
	return UTSArray.fromNative(kotlinArray)
}

export function sdkInit(){
	const app = UTSAndroid.getAppContext() as Application;
	const activity = UTSAndroid.getUniActivity();
	FitCloudSDK.sdkInit(activity!,app);
}